# Generated by Django 4.1.1 on 2022-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='designation',
            field=models.CharField(max_length=50, verbose_name='Название города'),
        ),
    ]
