# Generated by Django 4.1.1 on 2022-10-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_alter_city_options_alter_city_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Вакансия')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='designation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
