# Generated by Django 4.1.1 on 2022-10-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_vacancy_alter_city_designation_alter_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
