# Generated by Django 4.1.1 on 2022-10-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('designation', models.CharField(max_length=250, verbose_name='Наименование вакансии')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('description', models.TextField(max_length=250, verbose_name='Подробное описание вакансии')),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.city', verbose_name='Город')),
                ('vacancy', models.ForeignKey(default='Удаленная работа', on_delete=django.db.models.deletion.SET_DEFAULT, to='search_engine.vacancy', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
