# Generated by Django 4.1.1 on 2022-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_vacancyparsed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='vacancyparsed',
            options={'verbose_name': 'вакансия', 'verbose_name_plural': 'Собранные вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancyparsed',
            name='description',
            field=models.TextField(verbose_name='Подробное описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancyparsed',
            name='designation',
            field=models.CharField(max_length=250, verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancyparsed',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
