# Generated by Django 4.1.2 on 2022-10-25 21:06

from django.db import migrations, models
import django.db.models.deletion
import search_engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=search_engine.models.get_default_urls_json)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_engine.city', verbose_name='Город')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_engine.specialization', verbose_name='Специализация')),
            ],
            options={
                'unique_together': {('city', 'specialization')},
            },
        ),
    ]
