# Generated by Django 4.1.2 on 2022-10-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_specialization_alter_city_options_alter_city_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'специализацию', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=70, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=70, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('time_stamp', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_engine.city', verbose_name='Город')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_engine.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'специализацию',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
