# Generated by Django 4.1.2 on 2022-10-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_alter_specialization_options_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
